services:

  gestionUsuarios-web-service:
    image: tomcat:10.0.6
    command: sh -c "catalina.sh jpda run"
    ports:
      - 8888:8080
      - 8000:8000
    volumes:
      - ./webservices/:/usr/local/tomcat/webapps/
    environment:
      - JPDA_ADDRESS=8000
      - JPDA_TRANSPORT=dt_socket
      - JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    networks:
      gestionUsuarios-network:
        aliases:
          - tomcat

  gestionUsuarios_db:
    image: postgres:13.3
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=1q2w3e4R
      - POSTGRES_USER=admin
      - POSTGRES_DB=gestionUsuarios
    networks:
      gestionUsuarios-network:
        aliases:
          - postgres

networks:
  gestionUsuarios-network:
    driver: bridge


     
